### ISSUE TITLE
Relative path for wix 

### ISSUE THREAD

**Issue by rinkypandya** [jenkinsci/wix-plugin#10]
I am trying to build a wix project through jenkins. I am not sure what format I should pass path in "Source files" text box. It says relative path but I am not sure about format. 

My wxs file location is C:\Program Files (x86)\Jenkins\workspace\TestProject\ui.project\ProjCurrent\Analysis\WebSetupWix\Product.wxs.

Thank you.

**Comment by rollinhand** [comment]
Please have a look at [WIX Toolset Plugin Wiki](https://wiki.jenkins.io/display/JENKINS/WIX+Toolset+Plugin).
There are detailed instructions on using relative paths. So if _Product.wxs_ is your only configuration file, use an Ant style file pattern like */Product.wxs or if you have multiple configuration files use _ui.project/ProjCurrent/Analysis/WebSetupWix/Product.wxs_.

**Comment by rinkypandya** [comment]
Thank you. So jenkin will automatically go to workspace directory and if I use path  TestProject\ui.project\ProjCurrent\Analysis\WebSetupWix\Product.wxs, then it should get picked up. correct?

**Comment by rollinhand** [comment]
Sure, it always searches your local workspace configured in your Jenkins project.

**Comment by rinkypandya** [comment]
Thanks. I still throws this error. 

[wix] Enable Debug: true
[wix] Detecting environment variables...
[wix] Found sources: 0
[wix] Initializing tools...
[wix] Environment variables are not automatically added as parameters.
[wix] Environment variables are not automatically added as parameters.
[wix] Wix Toolset plugin is running in slave mode.
[wix] Do not test if toolset is installed.
[wix] Starting compile process...
[wix] SEVERE: 0
[wix] Stacktrace follows:
java.lang.ArrayIndexOutOfBoundsException: 0
	at de.berg.systeme.jenkins.wix.Toolset.compile(Toolset.java:142)
	at de.berg.systeme.jenkins.wix.WixToolsetBuilder.perform(WixToolsetBuilder.java:164)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Build step 'WIX Toolset' changed build result to FAILURE
Build step 'WIX Toolset' marked build as failure
Finished: FAILURE

**Comment by rollinhand** [comment]
The Stacktrace tells you that it has not found any sources. This means you configured your relative path wrong. Add a screenshot if you need further help.
