### ISSUE TITLE
Slave mode - on compiling getting an error that is not possible debug

### ISSUE THREAD

**Issue by pulphix** [jenkinsci/wix-plugin#7]
On version 1.12 when I compile I'm getting an error, I cannot understand what is the issue:
[wix] Enable Debug: true
[wix] Detecting environment variables...
[wix] Found sources: 0
[wix] Initializing tools...
[wix] Environment variables are not automatically added as parameters.
[wix] Environment variables are not automatically added as parameters.
[wix] Wix Toolset plugin is running in slave mode.
[wix] Do not test if toolset is installed.
[wix] Starting compile process...
[wix] SEVERE: 0
[wix] Stacktrace follows:
java.lang.ArrayIndexOutOfBoundsException: 0
	at de.berg.systeme.jenkins.wix.Toolset.compile(Toolset.java:142)
	at de.berg.systeme.jenkins.wix.WixToolsetBuilder.perform(WixToolsetBuilder.java:164)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)
Build step 'WIX Toolset' changed build result to UNSTABLE
Build step 'WIX Toolset' marked build as failure

**Comment by rollinhand** [comment]
This is easy to answer. As you can see on third line, it could not find any source file as input for compilation:
[wix] Found sources: 0
But it is bad code at this point, because it is failing with an ArrayIndexOutOfBoundsException.

**Comment by pulphix** [comment]
Which file is looking for?
the application source or the wsx file?

**Comment by rollinhand** [comment]
It is looking for the wsx files which are defined as fileset pattern oder relative path. Source files can be one or more...

**Comment by pulphix** [comment]
Changing path on the path like
        <File Id="ffmpegsumo.dll" Source="..\..\build\production\win32\ffmpegsumo.dll" />
solved the issue

**Comment by rollinhand** [comment]
Thanks. Fix for ArrayIndexOutOfBoundsException is also pushed and will be released with 1.13.

**Comment by pulphix** [comment]
Request to be reopen
The problem seam that in the current configuration the slave flag is not anymore present, can that cause the issue?
